[package]
name = "clipboard"
version = "0.1.0"
authors = ["Manikandan Sundararajan <mani@hey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = "0.4.5"
lazy_static = "1.4.0"